[mypy]
ignore_missing_imports = True
exclude = tests/

[mypy-cks_runtime.core_api.*]
disallow_untyped_defs = True
disallow_any_generics = True
warn_return_any = True
warn_unreachable = True

[mypy-cks_runtime.diagnostics.*]
disallow_untyped_defs = True

[mypy-cks_runtime.dispatcher.*]
disallow_untyped_defs = True

[mypy-cks_runtime.events.*]
disallow_untyped_defs = True

[mypy-cks_runtime.execution.*]
disallow_untyped_defs = True

[mypy-cks_runtime.metrics.*]
disallow_untyped_defs = True

[mypy-cks_runtime.session.*]
disallow_untyped_defs = True

[mypy-cks_runtime.transaction.*]
disallow_untyped_defs = True